### ISSUE TITLE
Using multiple sources breaks output

### ISSUE THREAD

**Issue by jacobisaliveandwell** [asyncon/setuptools-pipfile#2]
I'm using multiple sources and specifying them within the config, which is resulting in odd version specifications:

```toml
[[source]]
# PyPi Repository
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
boto3 = {version = "*", index = "pypi"}
```

```python
from pprint import pprint
pprint(vars(distribution))
```

```plain
'install_requires': ['boto3@ https://pypi.org/simple/boto3/'],
```

It looks like `install_requires` [shouldn't have any index related metadata in it](https://packaging.python.org/discussions/install-requires-vs-requirements/), and that should just be `['boto3']`.
